import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Sidebar for documentation
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
